launch:
  # The following are the default values for the launch configuration
  # for more informations look at https://www.gradio.app/docs/interface 
  server_port: 7860
  server_name: 0.0.0.0
  inline: false
  inbrowser: false
  share : false
  debug : false
  max_threads: 40
  quiet: false
  auth:
    auth_enabled: false
    auth_username: admin
    auth_password: admin
  auth_message: null
  prevent_thread_lock : false
  show_error : false
  show_tips : false
  favicon_path : null
  ssl_keyfile : null
  ssl_certfile : null
  ssl_keyfile_password : null
  ssl_verify : false
  show_api : false
  allowed_paths : null
  blocked_paths : null
  root_path : ''
  app_kwargs : null
  
queue:
  # The following are the default values for the queue configuration
  # for more informations look at hhttps://www.gradio.app/docs/interface
  concurrency_count : 1
  status_update_rate : 'auto'
  api_open : null
  max_size : null
  
layout:
  header:  scraibe/app/header.html
  footer: null
  logo: scraibe/app/logo.svg
model:
  whisper_model : null
  dia_model: null
advanced:
  timeout: 300 #seconds e.g. 5 minutes
