name: Auto Label PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs: 
      all-labels: ${{ steps.label-the-PR.outputs.all-labels }}
    steps:
      - name: Apply Labels
        id: label-the-PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true