name: Mirror and run GitLab CI

on: [push, delete]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git-dmz.thuenen.de/kida/i2-skills-beratungsstelle/scraibe"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "git-dmz.thuenen.de"
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }} 
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
