name: Run tests

on:
 push:
  
  #pull_request:
    #branches: ['main', 'develop']

  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
             pip install -r setup.py 
             pip install pytest

           

      - name: Run pytest
        
        run: |
           echo "${{ secrets.HF_TOKEN }}" >> scraibe/.pyannotetoken
           pytest 
           